### ISSUE TITLE
Queue error

### ISSUE THREAD

**Issue by yurri87** [dc740/AutoHotPy#7]
Hi!

\AutoHotPy.py", line 103, in __init__
    self.kb_queue = Queue.Queue()
AttributeError: 'function' object has no attribute 'Queue'

what could be the cause of the error?

**Comment by lekary** [comment]
I changed from "Queue.Queue" to "queue.Queue"

**Comment by dc740** [comment]
I need to update the code. Queue (uppercase) was used back in python 2. I need to update the code for Python 3. And yes, changing it to lower case fixes it, since that will work in the newer python versions.

**Comment by dc740** [comment]
I pushed the changes. Let me know if it doesn't work.

Python 2 is no longer supported in this project.
