### ISSUE TITLE
Loss of control over a computer when a macro is playing

### ISSUE THREAD

**Issue by iNovenkij** [dc740/AutoHotPy#9]
Hi. Thank You for your job. I find one problem. 

Description Bug: 
1) I run script _Example8-Macros4 - Auto-repeating macros.py_
2) Press F1 for macros start playng. I see in console sequence _ABCABCABC...._ 
3) Press Escape 

Expected Result: The script stopped
Actual Result: The script continues to run. And now I can't stop the macros by pressing on F1. And can't stop script by pressing Escape. I can't move cursor mouse. 
The macro continues to run indefinitely. Computer control lost. 
I can only press "reset"

**Comment by dc740** [comment]
Hi,
the tool does not handle multithreading for you. You have to manually write the code to execute in several threads, so you can send the exit command to the thread that is running your commands. I believe someone else already did this in another issue.
